kind: ConfigMap
apiVersion: v1
metadata:
  ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      kind: Sock
      name: long-sock
      uid: long-sock-uid
  name: sock-map
  namespace: gc-test
  labels:
    gcTestParticipant: "true"
